"""Render the harbor job configs for a SkillFlow arm.

The arms are generated rather than committed. Two reasons, both learned the
hard way:

* a committed config carries an API key, and 285 of them carried the same one;
* two arms of a paired comparison that are written by hand differ in ways
  nobody notices -- a throttled turn limit, a missing template path -- and the
  resulting number still looks plausible.

Here the bare and skill arms are produced from one function with one flag, so
they cannot differ except in the flag, and the key is read from the
environment at run time and never written to disk.

Invoked as ``recuris skillflow render-configs``.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from recuris.paths import PathError, external_root, resolve_skill_memory

from .templates import ROUTING_POLICIES, family_slug, resolve_template

AGENT_IMPORT_PATH = "libs.harbor_noinstall_agents.agents:NoInstallQwenCode"

HEADER = """# Generated by `recuris skillflow render-configs`. Do not edit by hand:
# regenerate instead, so that the bare and skill arms cannot drift apart.
#
# arm:      {arm}
# routing:  {routing}
# family:   {family}
# template: {template}
"""


def discover_families(tasks_root: Path) -> list[Path]:
    """Task families are the immediate subdirectories that contain tasks."""
    if not tasks_root.is_dir():
        raise PathError(
            f"SkillFlow task set not found at {tasks_root}. "
            "Run `bash third_party/skillflow/setup.sh`, or set RECURIS_SKILLFLOW_TASKS."
        )
    return sorted(p for p in tasks_root.iterdir() if p.is_dir() and not p.name.startswith("_"))


def render_one(
    *,
    family: Path,
    arm: str,
    model: str,
    base_url: str,
    package: Path | None,
    routing: str,
    concurrency: int,
    tasks_root: Path,
) -> str:
    template = (
        resolve_template(family.name, package, routing) if arm == "skill" else None
    )
    lines = [
        HEADER.format(
            arm=arm,
            routing=routing if arm == "skill" else "n/a",
            family=family.name,
            template=template.name if template else "none (bare control)",
        ),
        f"job_name: recuris-{arm}-{family_slug(family.name)}",
        # One directory per arm. Harbor's default puts every job in `jobs/`,
        # and two arms sharing a directory is how one arm's results get scored
        # as the other's.
        f"jobs_dir: jobs/{arm}",
        "",
        "agents:",
        f"  - import_path: {AGENT_IMPORT_PATH}",
        f"    model_name: {model}",
        "    kwargs:",
        # Read from the process environment by harbor at run time. Never a
        # literal: a committed config must not be able to carry a credential.
        "      api_key: ${OPENAI_API_KEY}",
        f'      base_url: "{base_url}"',
    ]
    if template is not None:
        lines.append(f'      prompt_template_path: "{template.as_posix()}"')
    lines += [
        "",
        "environment:",
        "  allow_internet: true",
        "  force_build: false",
        # harbor's default is --rmi all, which deletes the task image after the
        # job. Rebuilding it costs far more than the disk it saves.
        "  delete: false",
        "",
        "orchestrator:",
        "  type: local",
        f"  n_concurrent_trials: {concurrency}",
        "  quiet: true",
        "",
        "datasets:",
        # Absolute, like the template path above. A relative dataset path
        # resolves against harbor's working directory, which is not the same
        # place for everyone, and the failure reads as "no tasks found".
        f'  - path: "{family.resolve().as_posix()}/"',
        "",
    ]
    return "\n".join(lines)


def build_parser(prog: str = "recuris skillflow render-configs") -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog=prog, description=__doc__)
    ap.add_argument("--arm", choices=("bare", "skill"), required=True)
    ap.add_argument("--model", required=True, help="model id as harbor expects it")
    ap.add_argument(
        "--base-url",
        default=os.environ.get("OPENAI_BASE_URL", ""),
        help="OpenAI-compatible endpoint; defaults to $OPENAI_BASE_URL",
    )
    ap.add_argument("--skill-memory", default="skillflow")
    ap.add_argument(
        "--routing",
        choices=ROUTING_POLICIES,
        default="default",
        help="'default' is model-agnostic; 'frozen_insample' reproduces the "
        "reported arm and applies six per-family overrides that were selected "
        "in-sample; see the README",
    )
    ap.add_argument("--concurrency", type=int, default=3)
    ap.add_argument("--out", required=True, help="directory to write configs into")
    ap.add_argument(
        "--tasks-root",
        default=os.environ.get("RECURIS_SKILLFLOW_TASKS", ""),
        help="the SkillFlow task set; defaults to $RECURIS_SKILLFLOW_TASKS, "
        "then external/SkillFlow/test_tasks/test_tasks",
    )
    ap.add_argument("--families", nargs="*", default=None, help="render only these families")
    return ap


def main(argv: list[str] | None = None) -> int:
    ap = build_parser()
    args = ap.parse_args(argv)

    if not args.base_url:
        ap.error("--base-url is required (or set OPENAI_BASE_URL)")

    tasks_root = (
        Path(args.tasks_root)
        if args.tasks_root
        else external_root() / "SkillFlow" / "test_tasks" / "test_tasks"
    )
    try:
        families = discover_families(tasks_root)
        package = resolve_skill_memory(args.skill_memory) if args.arm == "skill" else None
    except PathError as exc:
        ap.error(str(exc))

    if args.families:
        wanted = set(args.families)
        families = [f for f in families if f.name in wanted]
        unknown = wanted - {f.name for f in families}
        if unknown:
            ap.error(f"no such families under {tasks_root}: {sorted(unknown)}")
    if not families:
        ap.error(f"no task families found under {tasks_root}")

    if args.arm == "skill" and args.routing == "frozen_insample":
        print(
            "[recuris] routing=frozen_insample: six families use a template that "
            "was chosen by reading their own scores. Those six are in-sample; "
            "see the README before quoting a number from this arm.",
            file=sys.stderr,
        )

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for family in families:
        text = render_one(
            family=family,
            arm=args.arm,
            model=args.model,
            base_url=args.base_url,
            package=package,
            routing=args.routing,
            concurrency=args.concurrency,
            tasks_root=tasks_root,
        )
        path = out / f"{args.arm}_{family_slug(family.name)}.yaml"
        path.write_text(text, encoding="utf-8")
        print(f"[recuris] {path}")
    print(f"[recuris] {len(families)} configs written to {out}")
    # The agent these configs name lives in SkillFlow's own tree and harbor
    # imports it by Python path, so the run fails with "No module named 'libs'"
    # unless SkillFlow is importable. Print the command that works rather than
    # leave the reader to find that out from a TaskGroup traceback.
    skillflow_root = tasks_root.parent
    if skillflow_root.name == "test_tasks":
        skillflow_root = skillflow_root.parent
    print(
        "[recuris] run them one at a time, with SkillFlow importable:\n"
        f"  export PYTHONPATH={skillflow_root}\n"
        f'  for cfg in {out}/{args.arm}_*.yaml; do harbor run -c "$cfg" --yes; done'
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
