"""Fail-closed protection for the Skill Memory packages a campaign must not edit.

A campaign edits a *candidate* package. It must never edit a package that has
already been settled, because doing so would silently invalidate every number
measured against it. This module makes that a structural guarantee rather than
a convention:

* ``champions.lock.json`` records the exact byte content of each protected
  package -- per-file SHA-256 and size, plus one aggregate over the whole set;
* ``verify`` recomputes the tree and refuses to proceed on any added, deleted
  or modified file;
* ``assert_mutation_paths_safe`` is called before the driver creates any
  writable directory, and rejects a path that overlaps a protected asset or the
  lock file itself.

The aggregate the lock must match lives in ``integrity/anchors.json`` at the
repository root, not in a constant compiled into this file. That file is
regenerated by ``scripts/reanchor_integrity.py`` and its contents are checked in
CI, so an anchor change is a reviewable diff rather than an edit nobody sees.
Keeping the anchor outside the writable lock is the point: a lock that vouched
for itself would protect nothing.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path

from recuris.paths import repo_root, skill_memory_root

HERE = Path(__file__).resolve().parent
ROOT = repo_root()
DEFAULT_LOCK = skill_memory_root() / "champions.lock.json"
ANCHORS_PATH = ROOT / "integrity" / "anchors.json"

IGNORED_DIRS = {"__pycache__", ".pytest_cache"}
IGNORED_SUFFIXES = {".pyc", ".pyo"}


class ChampionIntegrityError(RuntimeError):
    """A protected package or mutation boundary is unsafe."""


def _ignored(path: Path) -> bool:
    return any(part in IGNORED_DIRS for part in path.parts) or path.suffix in IGNORED_SUFFIXES


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _tree(root: Path) -> dict[str, dict[str, int | str]]:
    if not root.is_dir():
        raise ChampionIntegrityError(f"protected package is missing: {root}")
    files: dict[str, dict[str, int | str]] = {}
    for path in sorted(root.rglob("*")):
        if path.is_file() and not _ignored(path.relative_to(root)):
            rel = path.relative_to(root).as_posix()
            files[rel] = {"sha256": _sha256(path), "bytes": path.stat().st_size}
    return files


def _aggregate(packages: dict[str, dict]) -> str:
    rows: list[str] = []
    for package in sorted(packages):
        for rel, meta in sorted(packages[package]["files"].items()):
            rows.append(f"{package}/{rel}:{meta['sha256']}")
    return hashlib.sha256("\n".join(rows).encode("utf-8")).hexdigest()


def load_anchors(path: Path = ANCHORS_PATH) -> dict:
    """Read the reviewed anchor file: which packages are protected, and their digest."""
    path = Path(path)
    if not path.is_file():
        raise ChampionIntegrityError(
            f"integrity anchors are missing: {path}. "
            "Run `python scripts/reanchor_integrity.py` after a deliberate "
            "change to a protected package, and commit the result."
        )
    anchors = json.loads(path.read_text(encoding="utf-8"))
    targets = anchors.get("packages")
    if not isinstance(targets, dict) or not targets:
        raise ChampionIntegrityError(f"{path}: 'packages' must be a non-empty object")
    digest = anchors.get("tree_sha256")
    if not isinstance(digest, str) or len(digest) != 64:
        raise ChampionIntegrityError(f"{path}: 'tree_sha256' must be a SHA-256 hex digest")
    for name, count in targets.items():
        rel = Path(name)
        if rel.is_absolute() or ".." in rel.parts or rel.as_posix() != name:
            raise ChampionIntegrityError(f"{path}: unsafe package path {name!r}")
        if not isinstance(count, int) or isinstance(count, bool) or count < 1:
            raise ChampionIntegrityError(f"{path}: {name} file count must be a positive integer")
    return anchors


def default_targets(path: Path = ANCHORS_PATH) -> tuple[Path, ...]:
    return tuple(Path(name) for name in sorted(load_anchors(path)["packages"]))


def build_lock(targets: Iterable[Path] | None = None) -> dict:
    packages: dict[str, dict] = {}
    for relative in targets if targets is not None else default_targets():
        relative = Path(relative)
        files = _tree((ROOT / relative).resolve())
        packages[relative.as_posix()] = {
            "files": files,
            "file_count": len(files),
            "bytes": sum(int(meta["bytes"]) for meta in files.values()),
        }
    lock = {
        "schema_version": 1,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "packages": packages,
    }
    lock["tree_sha256"] = _aggregate(packages)
    return lock


def write_lock(path: Path = DEFAULT_LOCK, *, force: bool = False) -> dict:
    """Write the lock. Refuses to overwrite unless explicitly forced.

    Overwriting is what re-anchoring means, so it is allowed -- but only from
    ``scripts/reanchor_integrity.py``, which also rewrites the anchor file in
    the same operation. Silently regenerating one without the other is how a
    lock stops meaning anything.
    """
    path = Path(path).resolve()
    if path.exists() and not force:
        raise ChampionIntegrityError(
            f"refusing to overwrite existing lock: {path}. "
            "Use scripts/reanchor_integrity.py, which updates the anchor too."
        )
    lock = build_lock()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(lock, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return lock


def load_lock(path: Path = DEFAULT_LOCK) -> dict:
    path = Path(path)
    if not path.is_file():
        raise ChampionIntegrityError(f"champion lock is missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def protected_roots(anchors_path: Path = ANCHORS_PATH) -> tuple[Path, ...]:
    # Derived from the reviewed anchor file, never from the writable lock.
    return tuple((ROOT / rel).resolve() for rel in default_targets(anchors_path))


def protected_paths(lock_path: Path = DEFAULT_LOCK) -> tuple[Path, ...]:
    """Every content and trust anchor that mutation code must never touch."""
    return (*protected_roots(), Path(lock_path).resolve(), ANCHORS_PATH.resolve())


def _validate_lock(lock: dict, anchors: dict) -> None:
    problems: list[str] = []
    expected_counts = anchors["packages"]
    expected_names = set(expected_counts)
    if lock.get("schema_version") != 1:
        problems.append("schema_version must be exactly 1")
    packages = lock.get("packages")
    if not isinstance(packages, dict) or set(packages) != expected_names:
        problems.append(f"packages must be exactly {sorted(expected_names)}")
        packages = packages if isinstance(packages, dict) else {}
    for relative in sorted(expected_names):
        package = packages.get(relative)
        if not isinstance(package, dict):
            continue
        files = package.get("files")
        if not isinstance(files, dict) or not files:
            problems.append(f"{relative}: files must be a non-empty object")
            continue
        if len(files) != expected_counts[relative]:
            problems.append(
                f"{relative}: expected {expected_counts[relative]} files, got {len(files)}"
            )
        for rel, meta in files.items():
            rel_path = Path(rel)
            if (not isinstance(rel, str) or not rel or rel_path.is_absolute() or
                    ".." in rel_path.parts or rel_path.as_posix() != rel):
                problems.append(f"{relative}: unsafe/non-canonical file path {rel!r}")
                continue
            if not isinstance(meta, dict):
                problems.append(f"{relative}/{rel}: metadata must be an object")
                continue
            digest = meta.get("sha256")
            size = meta.get("bytes")
            if (not isinstance(digest, str) or len(digest) != 64 or
                    any(ch not in "0123456789abcdef" for ch in digest)):
                problems.append(f"{relative}/{rel}: invalid sha256")
            if not isinstance(size, int) or isinstance(size, bool) or size < 0:
                problems.append(f"{relative}/{rel}: invalid byte count")
        if package.get("file_count") != len(files):
            problems.append(f"{relative}: file_count is inconsistent")
        if package.get("bytes") != sum(
                int(meta.get("bytes", -1)) for meta in files.values()
                if isinstance(meta, dict) and isinstance(meta.get("bytes"), int)):
            problems.append(f"{relative}: byte total is inconsistent")
    if packages and not problems:
        calculated = _aggregate(packages)
        if lock.get("tree_sha256") != calculated:
            problems.append("lock aggregate is internally inconsistent")
    if lock.get("tree_sha256") != anchors["tree_sha256"]:
        problems.append(
            "lock tree SHA-256 does not match integrity/anchors.json. "
            "A protected package changed: re-anchor deliberately, or revert."
        )
    if problems:
        raise ChampionIntegrityError("invalid champion lock:\n  " + "\n  ".join(problems))


def verify(path: Path = DEFAULT_LOCK) -> dict:
    anchors = load_anchors()
    lock = load_lock(path)
    _validate_lock(lock, anchors)
    problems: list[str] = []
    current: dict[str, dict] = {}
    for relative, expected in lock["packages"].items():
        try:
            files = _tree((ROOT / relative).resolve())
        except ChampionIntegrityError as exc:
            problems.append(str(exc))
            continue
        expected_files = expected["files"]
        for rel in sorted(set(expected_files) | set(files)):
            if rel not in files:
                problems.append(f"DELETED {relative}/{rel}")
            elif rel not in expected_files:
                problems.append(f"ADDED {relative}/{rel}")
            elif files[rel]["sha256"] != expected_files[rel]["sha256"]:
                problems.append(f"MODIFIED {relative}/{rel}")
        current[relative] = {
            "files": files,
            "file_count": len(files),
            "bytes": sum(int(meta["bytes"]) for meta in files.values()),
        }
    if _aggregate(current) != lock.get("tree_sha256"):
        problems.append("aggregate tree SHA-256 differs from champions.lock.json")
    if problems:
        raise ChampionIntegrityError("champion integrity violation:\n  " + "\n  ".join(problems))
    return {
        "ok": True,
        "tree_sha256": lock["tree_sha256"],
        "packages": {rel: data["file_count"] for rel, data in lock["packages"].items()},
    }


def _overlap(a: Path, b: Path) -> bool:
    a = a.resolve()
    b = b.resolve()
    return a == b or a.is_relative_to(b) or b.is_relative_to(a)


def assert_mutation_paths_safe(paths: Iterable[Path], lock_path: Path = DEFAULT_LOCK) -> None:
    for raw in paths:
        candidate = Path(raw).resolve()
        for protected in protected_paths(lock_path):
            if _overlap(candidate, protected):
                raise ChampionIntegrityError(
                    f"mutation path overlaps protected asset: {candidate} <-> {protected}"
                )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    args = parser.parse_args()
    result = verify(args.lock)
    print(f"CHAMPION INTEGRITY OK tree_sha256={result['tree_sha256']}")


if __name__ == "__main__":
    main()
